FROM golang:1.18.4-buster as builder

# Workdir
WORKDIR /

# Add current working directory
COPY . /

# Build
RUN go build -o ./clientAPI/cmd/main ./clientAPI/cmd/main.go

#========================== Runtime Image ==========================
FROM ubuntu:21.04

WORKDIR /app
COPY --from=builder clientAPI/cmd/main .

ENTRYPOINT ["/app/main"]