// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: portDomain/protos/port.proto

package port

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PortServiceClient is the client API for PortService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PortServiceClient interface {
	UploadPorts(ctx context.Context, opts ...grpc.CallOption) (PortService_UploadPortsClient, error)
	FindByKey(ctx context.Context, in *FindByKeyRequest, opts ...grpc.CallOption) (*FindByKeyResponse, error)
}

type portServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPortServiceClient(cc grpc.ClientConnInterface) PortServiceClient {
	return &portServiceClient{cc}
}

func (c *portServiceClient) UploadPorts(ctx context.Context, opts ...grpc.CallOption) (PortService_UploadPortsClient, error) {
	stream, err := c.cc.NewStream(ctx, &PortService_ServiceDesc.Streams[0], "/PortService/UploadPorts", opts...)
	if err != nil {
		return nil, err
	}
	x := &portServiceUploadPortsClient{stream}
	return x, nil
}

type PortService_UploadPortsClient interface {
	Send(*UpLoadPortRequest) error
	CloseAndRecv() (*Empty, error)
	grpc.ClientStream
}

type portServiceUploadPortsClient struct {
	grpc.ClientStream
}

func (x *portServiceUploadPortsClient) Send(m *UpLoadPortRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *portServiceUploadPortsClient) CloseAndRecv() (*Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *portServiceClient) FindByKey(ctx context.Context, in *FindByKeyRequest, opts ...grpc.CallOption) (*FindByKeyResponse, error) {
	out := new(FindByKeyResponse)
	err := c.cc.Invoke(ctx, "/PortService/FindByKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PortServiceServer is the server API for PortService service.
// All implementations must embed UnimplementedPortServiceServer
// for forward compatibility
type PortServiceServer interface {
	UploadPorts(PortService_UploadPortsServer) error
	FindByKey(context.Context, *FindByKeyRequest) (*FindByKeyResponse, error)
	mustEmbedUnimplementedPortServiceServer()
}

// UnimplementedPortServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPortServiceServer struct {
}

func (UnimplementedPortServiceServer) UploadPorts(PortService_UploadPortsServer) error {
	return status.Errorf(codes.Unimplemented, "method UploadPorts not implemented")
}
func (UnimplementedPortServiceServer) FindByKey(context.Context, *FindByKeyRequest) (*FindByKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindByKey not implemented")
}
func (UnimplementedPortServiceServer) mustEmbedUnimplementedPortServiceServer() {}

// UnsafePortServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PortServiceServer will
// result in compilation errors.
type UnsafePortServiceServer interface {
	mustEmbedUnimplementedPortServiceServer()
}

func RegisterPortServiceServer(s grpc.ServiceRegistrar, srv PortServiceServer) {
	s.RegisterService(&PortService_ServiceDesc, srv)
}

func _PortService_UploadPorts_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PortServiceServer).UploadPorts(&portServiceUploadPortsServer{stream})
}

type PortService_UploadPortsServer interface {
	SendAndClose(*Empty) error
	Recv() (*UpLoadPortRequest, error)
	grpc.ServerStream
}

type portServiceUploadPortsServer struct {
	grpc.ServerStream
}

func (x *portServiceUploadPortsServer) SendAndClose(m *Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *portServiceUploadPortsServer) Recv() (*UpLoadPortRequest, error) {
	m := new(UpLoadPortRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _PortService_FindByKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindByKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortServiceServer).FindByKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PortService/FindByKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortServiceServer).FindByKey(ctx, req.(*FindByKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PortService_ServiceDesc is the grpc.ServiceDesc for PortService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PortService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "PortService",
	HandlerType: (*PortServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindByKey",
			Handler:    _PortService_FindByKey_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadPorts",
			Handler:       _PortService_UploadPorts_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "portDomain/protos/port.proto",
}
